apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deployment
  namespace: example
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fast-api
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    labels:
      app: fast-api
    spec:
      containers:
        - args:
            - -m
            - debugpy
            - --listen
            - localhost:5678
            - -m
            - uvicorn
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - "5000"
            - --workers
            - "1"
          command:
            - python3
          env:
            - name: DATABASE_URL
              value: postgresql://hello_fastapi:hello_fastapi@postgres.example.svc/hello_fastapi_dev
          image: testing/fast-api-example:v2.5
          imagePullPolicy: Never
          name: fast-api
          ports:
            - containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 1G
            requests:
              cpu: 500m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
